apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: {{ .Values.namespace }}
  labels:
    app: blog
    version: latest
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: blog
      version: latest
  template:
    metadata:
      name: blog
      labels:
        app: blog
        version: latest
    spec:
      containers:
        - name: blog
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          resources: {{ .Values.resources | toYaml | nindent 12 }}
          ports:
            - containerPort: 80
      restartPolicy: Always
