apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: blog
spec:
  host: blog.live.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
  subsets:
    - name: v1
      labels:
        app: blog
        version: latest