apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: blog
  ports:
    - port: 8080
      name: http
      targetPort: 80
  type: ClusterIP