apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog
spec:
  gateways: {{ .Values.gateways | toYaml | nindent 4 }}
  hosts: {{ .Values.domains | toYaml | nindent 4 }}
  http:
    - name: "blog"
      route:
        - destination:
            host: blog.live.svc.cluster.local
            port:
              number: 8080
            subset: v1

