apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - {{ .Values.domain }}
  http:
    - name: "blog"
      route:
        - destination:
            host: blog.live.svc.cluster.local
            port:
              number: 8080
            subset: v1

