namespace: live
domain: blog.sungjunyoung.dev
gateway: istio-system/ingress-gateway
image:
  repository: public.ecr.aws/b0k0p6t5/blog
  tag: latest
  imagePullPolicy: Always
replicas: 2
resources:
  requests:
    cpu: 0.1
    memory: 100Mi
